/**
 * @file canvas.h
 * @brief Auto-generated header for canvas.cpp
 *
 * Generated by Header File Generator on 2026-07-04.
 * DO NOT EDIT — re-run the generator to update.
 */

#ifndef CANVAS_H
#define CANVAS_H

/* ─── Includes ────────────────────────────────────────────────────────── */

// #include <stdbool.h>
#include "bn_display.h"
#include "bn_sprite_ptr.h"

/* ─── Function Prototypes ─────────────────────────────────────────────── */

int get_canvas_point(bn::fixed percent, bool is_x);
void place_on_canvas(bn::sprite_ptr sprite, bn::fixed x_percent, bn::fixed y_percent);
bn::fixed_point get_canvas_pos(bn::fixed x_percent, bn::fixed y_percent);

#endif /* CANVAS_H */
