/**
 * @file game_state.h
 * @brief Auto-generated header for game_state.cpp
 *
 * Generated by Header File Generator on 2026-07-05.
 * DO NOT EDIT — re-run the generator to update.
 */

#ifndef GAME_STATE_H
#define GAME_STATE_H

#include "bn_string_view.h"

enum GameState
{
	Intro = 0,
	Game = 1,
	Result = 2
};

extern const bn::array<bn::string_view, 3> GameStateStrings{"Intro", "Game", "Result"};

#endif /* GAME_STATE_H */
