/**
 * @file main.h
 * @brief Auto-generated header for main.cpp
 *
 * Generated by Header File Generator on 2026-07-08.
 * DO NOT EDIT — re-run the generator to update.
 */

#ifndef MAIN_H
#define MAIN_H

/* ─── Includes ────────────────────────────────────────────────────────── */

#include <bn_string_view.h>
#include "game_state.h"

/* ─── Function Prototypes ─────────────────────────────────────────────── */

void init(void);
void state_update(void);
void switch_to_state(GameState newState);
void intro_init(void);
void game_init(void);
void intro_logic(void);
void game_logic(void);
void display_text(bn::fixed_point pos, bn::string_view text);

#endif /* MAIN_H */
