/**
 * @file main.h
 * @brief Auto-generated header for main.cpp
 *
 * Generated by Header File Generator on 2026-07-04.
 * DO NOT EDIT — re-run the generator to update.
 */

#ifndef MAIN_H
#define MAIN_H

/* ─── Includes ────────────────────────────────────────────────────────── */

// #include <stdbool.h>
#include "game_state.h"
#include "bn_sprite_ptr.h"

/* ─── Function Prototypes ─────────────────────────────────────────────── */

void place_on_canvas(bn::sprite_ptr sprite, float x_percent, float y_percent);
void switch_to_state(GameState newState);
void intro_display(void);
void intro_interraction(void);
void init(void);
void state_update(void);

#endif /* MAIN_H */
