/**
 * @file vector2.h
 * @brief Auto-generated header for vector2.cpp
 *
 * Generated by Header File Generator on 2026-07-14.
 * DO NOT EDIT — re-run the generator to update.
 */

#ifndef VECTOR2_H
#define VECTOR2_H

/* ─── Includes ────────────────────────────────────────────────────────── */

#include <bn_fixed_point.h>

namespace vector2
{
	bn::fixed_point rotate_vector(bn::fixed_point vector, int angle);
}

#endif /* VECTOR2_H */
